require("modules.autostart")
require("modules.binds")
require("modules.env")
require("modules.input")
require("modules.look")
require("modules.misc")
require("modules.monitors")
require("modules.windows")